$ErrorActionPreference = 'Stop'

# Conservative profile: strongest collision/spawn stability for difficult terrain.
$env:HVE_WALK_COLLISION_RADIUS = '0.31'
$env:HVE_SPAWN_SEARCH_RADIUS = '44'
$env:HVE_SPAWN_FLAT_RADIUS = '2'
$env:HVE_SPAWN_FLAT_MAX_DELTA = '1'
$env:HVE_MOUSE_SENS = '0.16'
$env:HVE_PLAYER_BUILD_HALF_WIDTH = '0.20'
$env:HVE_PLAYER_BUILD_HEIGHT = '1.62'
$env:HVE_CROSSHAIR_SIZE = '0.022'
$env:HVE_CROSSHAIR_GAP = '0.006'
$env:HVE_CROSSHAIR_OUTER_WIDTH = '4.0'
$env:HVE_CROSSHAIR_INNER_WIDTH = '2.2'
$env:HVE_CROSSHAIR_ALPHA = '0.98'
$env:HVE_PLACE_RATE = '15'
$env:HVE_PLACE_HOLD_DELAY = '0.12'
$env:HVE_LOWEND_CONTROLLER = '1'
$env:HVE_LOWEND_TARGET_MS = '22.2'
$env:HVE_LOWEND_HYST_MS = '0.8'
$env:HVE_LOWEND_MAX_LEVEL = '6'

$env:HVE_LARGE_MODE = '1'
$env:HVE_LARGE_TARGET_FPS = '55'
$env:HVE_LARGE_MIN_STREAM = '10'
$env:HVE_LARGE_MIN_UPLOAD = '6'
$env:HVE_LARGE_UPLOAD_BOOST = '20'
$env:HVE_QUALITY = '2'
$env:HVE_BLOCK_MAX = '220'
$env:HVE_VIEWDIST = '40'
$env:HVE_STREAM_MARGIN = '20'
$env:HVE_PRELOAD_RADIUS = '12'
$env:HVE_UPLOAD_BUDGET = '40'
$env:HVE_FAR_CLIP = '9000'

$env:HVE_PREDICTIVE_PREWARM = '1'
$env:HVE_PREWARM_CHUNKS = '8'
$env:HVE_PREWARM_SENSITIVITY = '5.0'
$env:HVE_PREWARM_SMOOTHING = '0.18'
$env:HVE_STREAM_DUAL_QUEUE = '1'
$env:HVE_STREAM_NEAR_RING = '7'
$env:HVE_STREAM_NEAR_SHARE = '80'

$exe = Join-Path $PSScriptRoot 'build\Release\HighPerformanceVoxelEngine.exe'
Start-Process -FilePath $exe -WorkingDirectory $PSScriptRoot
Write-Host 'Started HighPerformanceVoxelEngine with CONSERVATIVE profile.'
