$ErrorActionPreference = 'Stop'

# EXTREME profile: tries to push maximal chunk generation during a 2-minute startup window.
# Warning: very high CPU/RAM/GPU usage expected.

$env:HVE_TRACE_RUNTIME = '1'
$env:HVE_QUALITY = '2'
$env:HVE_AUTO_HW_QUALITY = '0'
$env:HVE_LOWEND_CONTROLLER = '0'
$env:HVE_ADAPTIVE_STREAM_BUDGET = '0'

$env:HVE_STREAM_DISTANCE_CAP = '8192'
$env:HVE_VIEWDIST = '512'
$env:HVE_STREAM_MARGIN = '512'
$env:HVE_HEIGHT_CHUNKS = '96'
$env:HVE_PRELOAD_HEIGHT_CHUNKS = '32'

$env:HVE_UPLOAD_BUDGET = '4096'
$env:HVE_UPLOAD_HARD_CAP = '8192'
$env:HVE_UPLOAD_PUMP_CAP = '8192'

$env:HVE_STREAM_INFLIGHT_MAX = '32768'
$env:HVE_STREAM_ENQUEUE_MAX = '131072'
$env:HVE_STREAM_STEPS_MAX = '12'
$env:HVE_STREAM_STEPS_OVERLOAD_MAX = '8'
$env:HVE_STREAM_STEPS_WHILE_MOVING = '2'

$env:HVE_PRELOAD_RADIUS = '512'
$env:HVE_PRELOAD_TARGET_LAYERS = '2'
$env:HVE_PRELOAD_TARGET_CIRCULAR = '1'
$env:HVE_PRELOAD_MAX_SEC = '120'
$env:HVE_PRELOAD_BLOCKS_INPUT = '1'

$env:HVE_STARTUP_LOADING_OVERLAY = '1'
$env:HVE_LOADING_INPUT_BREAKOUT = '0'
$env:HVE_LOADING_OVERLAY_MAX_SEC = '0'
$env:HVE_STARTUP_FORCE_PRELOAD = '1'
$env:HVE_STARTUP_BLOCK_MIN_CHUNKS = '1000000'
$env:HVE_STARTUP_BLOCK_MAX_SEC = '120'
$env:HVE_STARTUP_BLOCK_STALL_SEC = '8'

$env:HVE_STARTUP_PERF_PROTECT_SEC = '0'
$env:HVE_STARTUP_STREAM = '512'
$env:HVE_STARTUP_UPLOAD_MIN = '4096'
$env:HVE_STARTUP_HEIGHT = '64'
$env:HVE_STARTUP_WARM_CHUNKS = '200000'
$env:HVE_STARTUP_STREAM_STEPS = '8'

$env:HVE_CHUNK_CATCHUP_ENABLED = '1'
$env:HVE_CHUNK_CATCHUP_TARGET = '1000000'
$env:HVE_CHUNK_CATCHUP_UPLOAD_BOOST = '2048'
$env:HVE_CHUNK_CATCHUP_STREAM_BONUS = '256'
$env:HVE_CHUNK_CATCHUP_STEPS_BONUS = '6'
$env:HVE_CHUNK_CATCHUP_DEFICIT_SOFT = '500000'
$env:HVE_CHUNK_CATCHUP_STREAM_BURST_MAX = '12'
$env:HVE_CHUNK_CATCHUP_UPLOAD_BURST_MAX = '8192'
$env:HVE_CHUNK_CATCHUP_MIN_FPS = '20'
$env:HVE_CHUNK_CATCHUP_MAX_FRAME_MS = '60'

$env:HVE_INSTANT_HUGE_SIGHT = '1'
$env:HVE_INSTANT_HUGE_REPOSITION = '1'
$env:HVE_INSTANT_HUGE_RADIUS = '1024'
$env:HVE_INSTANT_HUGE_VERTICAL = '256'
$env:HVE_MEGA_PRELOAD_CONTINUOUS = '1'
$env:HVE_MEGA_PRELOAD_PULSE_SEC = '0.25'
$env:HVE_MEGA_PRELOAD_RADIUS_STEP = '128'
$env:HVE_MEGA_PRELOAD_RADIUS_MAX = '4096'
$env:HVE_MEGA_PRELOAD_VERTICAL_STEP = '32'
$env:HVE_MEGA_PRELOAD_VERTICAL_MAX = '512'
$env:HVE_PRELOAD_BOOTSTRAP_MAX = '5000000'
$env:HVE_PRELOAD_FAR_STRIDE_BEGIN = '512'
$env:HVE_PRELOAD_FAR_STRIDE2_BEGIN = '768'

$env:HVE_DISABLE_UNLOAD = '1'
$env:HVE_CACHE_MARGIN = '2048'
$env:HVE_VERTICAL_RADIUS = '256'

$env:HVE_MAX_FIXED_STEPS = '3'
$env:HVE_RECOVERY_FIXED_STEPS = '1'
$env:HVE_FIXED_STEPS_WHILE_MOVING = '1'

$exe = Join-Path $PSScriptRoot 'build\Release\HighPerformanceVoxelEngine.exe'
Start-Process -FilePath $exe -WorkingDirectory $PSScriptRoot
Write-Host 'Started HighPerformanceVoxelEngine with MILLION_2MIN extreme profile.'
